const tabledata = [
  {
    key: 1,
    c1: "Time",
    l1: "/meets",
    c2: "Monday",
    l2: "",
    c3: "Tuesday",
    l3: "",
    c4: "Wednesday",
    l4: "",
    c5: "Thursday",
    l5: "",
    c6: "Friday",
    l6: "",
    c7: "Saturday",
    l7: "",
    c8: "Sunday",
    l8: `""`,
  },

  {
    key: 2,
    c1: "8 am",
    l1: "",
    c2: "Adv Eng Com",
    l2: "",
    c3: "Manufacturing T2",
    l3: "",
    c4: "Adv Eng Com",
    l4: "",
    c5: "Adv MOS T2",
    l5: "https://meet.google.com/exb-ngxc-xna?hs=224",
    c6: "Adv Eng Com",
    l6: "",
    c7: "",
    l7: "",
    c8: "",
    l8: `""`,
  },

  {
    key: 3,
    c1: "9 am",
    l1: "",
    c2: "Adv MOS L1",
    l2: "https://meet.google.com/cjm-tchw-kip",
    c3: "Heat Transfer L1",
    l3: "https://meet.google.com/hfg-mrvg-mxs",
    c4: "Adv MOS L1",
    l4: "https://meet.google.com/cjm-tchw-kip",
    c5: "Heat Transfer L1",
    l5: "https://meet.google.com/hfg-mrvg-mxs",
    c6: "",
    l6: "",
    c7: "Heat Transfer L1",
    l7: "https://meet.google.com/hfg-mrvg-mxs",
    c8: "",
    l8: `""`,
  },

  {
    key: 4,
    c1: "10 am",
    l1: "",
    c2: "manufacturing L1",
    l2: "",
    c3: "Mech & Machines L1",
    l3: "",
    c4: "manufacturing L1",
    l4: "",
    c5: "Mech & Machines L1",
    l5: "",
    c6: "manufacturing L1",
    l6: "",
    c7: "Mech & Machines L1",
    l7: "",
    c8: "",
    l8: `""`,
  },

  {
    key: 5,
    c1: "11 am",
    l1: "",
    c2: "",
    l2: "",
    c3: "Heat Transfer P3",
    l3: "",
    c4: "",
    l4: "",
    c5: "Manufacturing  P2",
    l5: "",
    c6: "",
    l6: "",
    c7: "",
    l7: "",
    c8: "",
    l8: ` ""`,
  },

  {
    key: 6,
    c1: "12 am",
    l1: "",
    c2: "",
    l2: "",
    c3: "Heat Transfer P3",
    l3: "",
    c4: "",
    l4: "",
    c5: "Manufacturing P2",
    l5: "",
    c6: "",
    l6: "",
    c7: "",
    l7: "",
    c8: "",
    l8: ` ""`,
  },

  {
    key: 7,
    c1: "1 am",
    l1: "",
    c2: "EVS L1",
    l2: "",
    c3: "",
    l3: "",
    c4: "EVS L1",
    l4: "",
    c5: "",
    l5: "",
    c6: "EVS L1",
    l6: "",
    c7: "",
    l7: "",
    c8: "",
    l8: `""`,
  },

  {
    key: 8,
    c1: "2 am",
    l1: "",
    c2: "B",
    l2: "",
    c3: "R",
    l3: "",
    c4: "E",
    l4: "",
    c5: "A",
    l5: "",
    c6: "K",
    l6: "",
    c7: "-F",
    l7: "",
    c8: "O",
    l8: `""`,
  },

  {
    key: 9,
    c1: "3 am",
    l1: "",
    c2: "",
    l2: "",
    c3: "",
    l3: "",
    c4: "",
    l4: "",
    c5: "",
    l5: "",
    c6: "",
    l6: "",
    c7: "",
    l7: "",
    c8: "",
    l8: `""`,
  },

  {
    key: 10,
    c1: "4 am",
    l1: "",
    c2: "Post Col Lit L1",
    l2: "",
    c3: "Adv MOS T3",
    l3: "",
    c4: "Post Col Lit L1",
    l4: "",
    c5: "Adv MOS T3",
    l5: "",
    c6: "Post Col Lit L1",
    l6: "",
    c7: "",
    l7: "",
    c8: "",
    l8: "",
  },
];

export default function handler(req, res) {
  res.status(200).json(tabledata);
}
